#version: "3"
services:
  vllm_gemma3_4b:
    image: vllm/vllm-openai
    ports:
      - "8001:8001"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    # volumes:
    #   - /home/a01088415234/models/gemma-3-4b-it:/models/gemma
    command: >
      --model google/gemma-3-4b-it
      --port 8001
      --gpu-memory-utilization 0.95
      --max-model-len 8192
      --max-num-seqs 10
      --max-num-batched-tokens 4096
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]