name: AI Docker Scheduling CD

on:
  schedule:
    - cron: '0 6 * * *'  # 매일 오후 3시 (KST)
  workflow_dispatch:

jobs:
  deploy:
    name: Run Deployment Script on GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_AI_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Remote Deployment Script
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_AI_DEV_HOST }} \
            "bash ~/scripts/deploy.sh"
