name: AI Docker CD Dev

on:
  workflow_run:
    workflows: ["AI Docker CI Dev"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Deploy FastAPI to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-ai-dev:latest" >> $GITHUB_ENV

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_AI_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_AI_DEV_HOST }} << 'EOF'
            docker pull ${{ env.IMAGE_TAG }}

            docker stop youtil-ai-dev || true
            docker rm youtil-ai-dev || true

            docker run -d --name youtil-ai-dev \
              -p 8000:8000 \
              ${{ env.IMAGE_TAG }}
          EOF