name: AI Docker CI Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set Docker Image Tag
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-ai-dev
          echo "IMAGE_TAG=${IMAGE}:${TIMESTAMP}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=${IMAGE}:latest" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GCP Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: Integration
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode and Save .env
        working-directory: Integration
        run: |
          echo "${{ secrets.ENV_DEV }}" | base64 --decode > .env

      - name: Build Docker Image
        working-directory: Integration
        run: |
          docker build -t ${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_LATEST }} .

      - name: Push Docker Images
        run: |
          docker push ${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_LATEST }}